import express from "express";
import { config } from "dotenv";
config();
import cors from "cors";
const app = express();
const port = process.env.PORT || 5000;
import adminRoutes from "./routes/admins/admin.routes.js";
import userRoutes from "./routes/users/user.routes.js";
import connection from "./connection/config.js";
import cookieParser from "cookie-parser";
connection();
app.use(cookieParser());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use("/uploads/", express.static("uploads/"));
app.use(cors());
adminRoutes(app);
userRoutes(app);
app.listen(port, () => {
  console.log(`The Server is runing on port http://localhost:${port}`);
});
